# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1l_ChernovaVV' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 1l_ChernovaVV
  pod 'Alamofire', '~> 5.0.0-beta.5'

  target '1l_ChernovaVVTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
